export default function TermsOfUse() {
    return (
        <main className="min-h-screen bg-[#FBF3F0] pt-32 pb-16 px-6">
            <div className="max-w-2xl mx-auto">

                {/* <div className="flex items-center gap-2 mb-6">
                    <span className="block w-7 h-px bg-[#B5838D]" />
                    <span className="text-[11px] tracking-[3px] uppercase text-[#B5838D] font-medium">
                        Legal
                    </span>
                </div> */}

                <h1 className="font-[family-name:var(--font-playfair)] text-4xl text-[#3A2F2F] mb-3">
                    Terms of Use
                </h1>
                <p className="text-xs text-[#3A2F2F]/40 mb-12">Last updated: April 2026</p>

                <div className="space-y-10 text-sm text-[#3A2F2F]/70 font-light leading-relaxed">

                    <section>
                        <h2 className="font-[family-name:var(--font-playfair)] text-xl text-[#3A2F2F] mb-3">
                            About SkinWise
                        </h2>
                        <p>
                            SkinWise is a personal, educational project created to help people build
                            simple skincare routines. By using this site, you agree to these terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="font-[family-name:var(--font-playfair)] text-xl text-[#3A2F2F] mb-3">
                            Not medical advice
                        </h2>
                        <p className="mb-3">
                            The content and recommendations provided by SkinWise are for educational
                            and informational purposes only. They do not constitute medical or
                            dermatological advice.
                        </p>
                        <p>
                            If you have a skin condition, allergy, or any medical concern, please
                            consult a qualified dermatologist or healthcare professional before
                            changing your skincare routine.
                        </p>
                    </section>

                    {/* <section>
                        <h2 className="font-[family-name:var(--font-playfair)] text-xl text-[#3A2F2F] mb-3">
                            AI-generated content
                        </h2>
                        <p>
                            Parts of your results are generated by Claude AI (Anthropic). While we
                            do our best to provide accurate and helpful recommendations, AI-generated
                            content may not always be perfect. Always use your own judgement and
                            patch-test new products before incorporating them into your routine.
                        </p>
                    </section> */}

                    <section>
                        <h2 className="font-[family-name:var(--font-playfair)] text-xl text-[#3A2F2F] mb-3">
                            Use of the site
                        </h2>
                        <p>
                            SkinWise is provided free of charge for personal use. You may not
                            reproduce, redistribute, or use any part of this site for commercial
                            purposes without permission.
                        </p>
                    </section>

                    {/* <section>
                        <h2 className="font-[family-name:var(--font-playfair)] text-xl text-[#3A2F2F] mb-3">
                            Changes to these terms
                        </h2>
                        <p>
                            These terms may be updated from time to time. Continued use of SkinWise
                            after any changes means you accept the updated terms.
                        </p>
                    </section> */}

                </div>
            </div>
        </main>
    );
}